/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KYCVerifier__factory } from "./KYCVerifier__factory";
export { PersonhoodVerifier__factory } from "./PersonhoodVerifier__factory";
export { SimplePersonaToken__factory } from "./SimplePersonaToken__factory";
